//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCrm.DepartmentsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartmentsService.IDepartmentsService")]
    public interface IDepartmentsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/AddNewDepartment", ReplyAction="http://tempuri.org/IDepartmentsService/AddNewDepartmentResponse")]
        void AddNewDepartment(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/AddNewDepartment", ReplyAction="http://tempuri.org/IDepartmentsService/AddNewDepartmentResponse")]
        System.Threading.Tasks.Task AddNewDepartmentAsync(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/UpdateDepartment", ReplyAction="http://tempuri.org/IDepartmentsService/UpdateDepartmentResponse")]
        void UpdateDepartment(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/UpdateDepartment", ReplyAction="http://tempuri.org/IDepartmentsService/UpdateDepartmentResponse")]
        System.Threading.Tasks.Task UpdateDepartmentAsync(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/DeleteDepartment", ReplyAction="http://tempuri.org/IDepartmentsService/DeleteDepartmentResponse")]
        void DeleteDepartment(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/DeleteDepartment", ReplyAction="http://tempuri.org/IDepartmentsService/DeleteDepartmentResponse")]
        System.Threading.Tasks.Task DeleteDepartmentAsync(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/GetDepartments", ReplyAction="http://tempuri.org/IDepartmentsService/GetDepartmentsResponse")]
        CrmModels.DepartmentDto[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/GetDepartments", ReplyAction="http://tempuri.org/IDepartmentsService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<CrmModels.DepartmentDto[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/GetDepartmentById", ReplyAction="http://tempuri.org/IDepartmentsService/GetDepartmentByIdResponse")]
        CrmModels.DepartmentDto GetDepartmentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentsService/GetDepartmentById", ReplyAction="http://tempuri.org/IDepartmentsService/GetDepartmentByIdResponse")]
        System.Threading.Tasks.Task<CrmModels.DepartmentDto> GetDepartmentByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartmentsServiceChannel : LightCrm.DepartmentsService.IDepartmentsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentsServiceClient : System.ServiceModel.ClientBase<LightCrm.DepartmentsService.IDepartmentsService>, LightCrm.DepartmentsService.IDepartmentsService {
        
        public DepartmentsServiceClient() {
        }
        
        public DepartmentsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewDepartment(CrmModels.DepartmentDto departmentDto) {
            base.Channel.AddNewDepartment(departmentDto);
        }
        
        public System.Threading.Tasks.Task AddNewDepartmentAsync(CrmModels.DepartmentDto departmentDto) {
            return base.Channel.AddNewDepartmentAsync(departmentDto);
        }
        
        public void UpdateDepartment(CrmModels.DepartmentDto departmentDto) {
            base.Channel.UpdateDepartment(departmentDto);
        }
        
        public System.Threading.Tasks.Task UpdateDepartmentAsync(CrmModels.DepartmentDto departmentDto) {
            return base.Channel.UpdateDepartmentAsync(departmentDto);
        }
        
        public void DeleteDepartment(CrmModels.DepartmentDto departmentDto) {
            base.Channel.DeleteDepartment(departmentDto);
        }
        
        public System.Threading.Tasks.Task DeleteDepartmentAsync(CrmModels.DepartmentDto departmentDto) {
            return base.Channel.DeleteDepartmentAsync(departmentDto);
        }
        
        public CrmModels.DepartmentDto[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<CrmModels.DepartmentDto[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public CrmModels.DepartmentDto GetDepartmentById(int id) {
            return base.Channel.GetDepartmentById(id);
        }
        
        public System.Threading.Tasks.Task<CrmModels.DepartmentDto> GetDepartmentByIdAsync(int id) {
            return base.Channel.GetDepartmentByIdAsync(id);
        }
    }
}
