//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCrm.ServiceReferenceDepartments {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDepartments.IDepartmentService")]
    public interface IDepartmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/AddNewDepartment", ReplyAction="http://tempuri.org/IDepartmentService/AddNewDepartmentResponse")]
        void AddNewDepartment(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/AddNewDepartment", ReplyAction="http://tempuri.org/IDepartmentService/AddNewDepartmentResponse")]
        System.Threading.Tasks.Task AddNewDepartmentAsync(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/UpdateDepartment", ReplyAction="http://tempuri.org/IDepartmentService/UpdateDepartmentResponse")]
        void UpdateDepartment(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/UpdateDepartment", ReplyAction="http://tempuri.org/IDepartmentService/UpdateDepartmentResponse")]
        System.Threading.Tasks.Task UpdateDepartmentAsync(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/DeleteDepartment", ReplyAction="http://tempuri.org/IDepartmentService/DeleteDepartmentResponse")]
        void DeleteDepartment(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/DeleteDepartment", ReplyAction="http://tempuri.org/IDepartmentService/DeleteDepartmentResponse")]
        System.Threading.Tasks.Task DeleteDepartmentAsync(CrmModels.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartments", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentsResponse")]
        CrmModels.DepartmentDto[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartments", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<CrmModels.DepartmentDto[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartmentById", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentByIdResponse")]
        CrmModels.DepartmentDto GetDepartmentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartmentById", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentByIdResponse")]
        System.Threading.Tasks.Task<CrmModels.DepartmentDto> GetDepartmentByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartmentServiceChannel : LightCrm.ServiceReferenceDepartments.IDepartmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentServiceClient : System.ServiceModel.ClientBase<LightCrm.ServiceReferenceDepartments.IDepartmentService>, LightCrm.ServiceReferenceDepartments.IDepartmentService {
        
        public DepartmentServiceClient() {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewDepartment(CrmModels.DepartmentDto departmentDto) {
            base.Channel.AddNewDepartment(departmentDto);
        }
        
        public System.Threading.Tasks.Task AddNewDepartmentAsync(CrmModels.DepartmentDto departmentDto) {
            return base.Channel.AddNewDepartmentAsync(departmentDto);
        }
        
        public void UpdateDepartment(CrmModels.DepartmentDto departmentDto) {
            base.Channel.UpdateDepartment(departmentDto);
        }
        
        public System.Threading.Tasks.Task UpdateDepartmentAsync(CrmModels.DepartmentDto departmentDto) {
            return base.Channel.UpdateDepartmentAsync(departmentDto);
        }
        
        public void DeleteDepartment(CrmModels.DepartmentDto departmentDto) {
            base.Channel.DeleteDepartment(departmentDto);
        }
        
        public System.Threading.Tasks.Task DeleteDepartmentAsync(CrmModels.DepartmentDto departmentDto) {
            return base.Channel.DeleteDepartmentAsync(departmentDto);
        }
        
        public CrmModels.DepartmentDto[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<CrmModels.DepartmentDto[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public CrmModels.DepartmentDto GetDepartmentById(int id) {
            return base.Channel.GetDepartmentById(id);
        }
        
        public System.Threading.Tasks.Task<CrmModels.DepartmentDto> GetDepartmentByIdAsync(int id) {
            return base.Channel.GetDepartmentByIdAsync(id);
        }
    }
}
