//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCrm.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDto", Namespace="http://schemas.datacontract.org/2004/07/CrmServices.Dtos")]
    [System.SerializableAttribute()]
    public partial class ServiceDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNewService", ReplyAction="http://tempuri.org/IService/AddNewServiceResponse")]
        void AddNewService(LightCrm.Service.ServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNewService", ReplyAction="http://tempuri.org/IService/AddNewServiceResponse")]
        System.Threading.Tasks.Task AddNewServiceAsync(LightCrm.Service.ServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateService", ReplyAction="http://tempuri.org/IService/UpdateServiceResponse")]
        void UpdateService(LightCrm.Service.ServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateService", ReplyAction="http://tempuri.org/IService/UpdateServiceResponse")]
        System.Threading.Tasks.Task UpdateServiceAsync(LightCrm.Service.ServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteService", ReplyAction="http://tempuri.org/IService/DeleteServiceResponse")]
        void DeleteService(LightCrm.Service.ServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteService", ReplyAction="http://tempuri.org/IService/DeleteServiceResponse")]
        System.Threading.Tasks.Task DeleteServiceAsync(LightCrm.Service.ServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetService", ReplyAction="http://tempuri.org/IService/GetServiceResponse")]
        LightCrm.Service.ServiceDto[] GetService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetService", ReplyAction="http://tempuri.org/IService/GetServiceResponse")]
        System.Threading.Tasks.Task<LightCrm.Service.ServiceDto[]> GetServiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : LightCrm.Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<LightCrm.Service.IService>, LightCrm.Service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewService(LightCrm.Service.ServiceDto service) {
            base.Channel.AddNewService(service);
        }
        
        public System.Threading.Tasks.Task AddNewServiceAsync(LightCrm.Service.ServiceDto service) {
            return base.Channel.AddNewServiceAsync(service);
        }
        
        public void UpdateService(LightCrm.Service.ServiceDto service) {
            base.Channel.UpdateService(service);
        }
        
        public System.Threading.Tasks.Task UpdateServiceAsync(LightCrm.Service.ServiceDto service) {
            return base.Channel.UpdateServiceAsync(service);
        }
        
        public void DeleteService(LightCrm.Service.ServiceDto service) {
            base.Channel.DeleteService(service);
        }
        
        public System.Threading.Tasks.Task DeleteServiceAsync(LightCrm.Service.ServiceDto service) {
            return base.Channel.DeleteServiceAsync(service);
        }
        
        public LightCrm.Service.ServiceDto[] GetService() {
            return base.Channel.GetService();
        }
        
        public System.Threading.Tasks.Task<LightCrm.Service.ServiceDto[]> GetServiceAsync() {
            return base.Channel.GetServiceAsync();
        }
    }
}
