//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCrm.DoctorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorServiceDto", Namespace="http://schemas.datacontract.org/2004/07/CrmServices.Dtos")]
    [System.SerializableAttribute()]
    public partial class DoctorServiceDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoctorService.IDoctorService")]
    public interface IDoctorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/AddNewDoctorService", ReplyAction="http://tempuri.org/IDoctorService/AddNewDoctorServiceResponse")]
        void AddNewDoctorService(LightCrm.DoctorService.DoctorServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/AddNewDoctorService", ReplyAction="http://tempuri.org/IDoctorService/AddNewDoctorServiceResponse")]
        System.Threading.Tasks.Task AddNewDoctorServiceAsync(LightCrm.DoctorService.DoctorServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/UpdateDoctorService", ReplyAction="http://tempuri.org/IDoctorService/UpdateDoctorServiceResponse")]
        void UpdateDoctorService(LightCrm.DoctorService.DoctorServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/UpdateDoctorService", ReplyAction="http://tempuri.org/IDoctorService/UpdateDoctorServiceResponse")]
        System.Threading.Tasks.Task UpdateDoctorServiceAsync(LightCrm.DoctorService.DoctorServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/DeleteDoctorService", ReplyAction="http://tempuri.org/IDoctorService/DeleteDoctorServiceResponse")]
        void DeleteDoctorService(LightCrm.DoctorService.DoctorServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/DeleteDoctorService", ReplyAction="http://tempuri.org/IDoctorService/DeleteDoctorServiceResponse")]
        System.Threading.Tasks.Task DeleteDoctorServiceAsync(LightCrm.DoctorService.DoctorServiceDto service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetService", ReplyAction="http://tempuri.org/IDoctorService/GetServiceResponse")]
        LightCrm.DoctorService.DoctorServiceDto[] GetService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetService", ReplyAction="http://tempuri.org/IDoctorService/GetServiceResponse")]
        System.Threading.Tasks.Task<LightCrm.DoctorService.DoctorServiceDto[]> GetServiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoctorServiceChannel : LightCrm.DoctorService.IDoctorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoctorServiceClient : System.ServiceModel.ClientBase<LightCrm.DoctorService.IDoctorService>, LightCrm.DoctorService.IDoctorService {
        
        public DoctorServiceClient() {
        }
        
        public DoctorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoctorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewDoctorService(LightCrm.DoctorService.DoctorServiceDto service) {
            base.Channel.AddNewDoctorService(service);
        }
        
        public System.Threading.Tasks.Task AddNewDoctorServiceAsync(LightCrm.DoctorService.DoctorServiceDto service) {
            return base.Channel.AddNewDoctorServiceAsync(service);
        }
        
        public void UpdateDoctorService(LightCrm.DoctorService.DoctorServiceDto service) {
            base.Channel.UpdateDoctorService(service);
        }
        
        public System.Threading.Tasks.Task UpdateDoctorServiceAsync(LightCrm.DoctorService.DoctorServiceDto service) {
            return base.Channel.UpdateDoctorServiceAsync(service);
        }
        
        public void DeleteDoctorService(LightCrm.DoctorService.DoctorServiceDto service) {
            base.Channel.DeleteDoctorService(service);
        }
        
        public System.Threading.Tasks.Task DeleteDoctorServiceAsync(LightCrm.DoctorService.DoctorServiceDto service) {
            return base.Channel.DeleteDoctorServiceAsync(service);
        }
        
        public LightCrm.DoctorService.DoctorServiceDto[] GetService() {
            return base.Channel.GetService();
        }
        
        public System.Threading.Tasks.Task<LightCrm.DoctorService.DoctorServiceDto[]> GetServiceAsync() {
            return base.Channel.GetServiceAsync();
        }
    }
}
